- id: pylint
  name: Run pylint on Python files
  entry: pylint
  language: system
  files: \.py$
  description: This hook runs pylint to check for Python code quality.

- id: htmlhint
  name: HTMLHint
  entry: htmlhint
  language: system
  files: \.html$
  description: This hook runs HTMLHint to check for HTML code quality.
