repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.16.3
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]

