# .pre-commit-config.yaml

# Liste des dépôts (repos) contenant les hooks
repos:
  - repo: local
    hooks:
      - id: pylint  # Le hook que nous voulons utiliser
        name: Pylint
        entry: pylint
        language: system
        types: [python]
        files: \.py$  # Ce hook ne s'exécute que sur les fichiers .py

  - repo:  local
    hooks:
      - id: htmlhint  # Le hook que nous voulons utiliser
        name: HTMLHint
        entry: pylint
        language: system
        types: [text]
        files: \.html$  # Ce hook ne s'exécute que sur les fichiers .html

