- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.15.0
  hooks:
    - id: pylint
      name: Pylint
      entry: pylint
      language: python
      files: \.py$

- repo: https://github.com/HTMLHint/HTMLHint.git
  rev: v0.15.0
  hooks:
    - id: htmlhint
      name: HTMLHint
      entry: htmlhint
      language: node
      files: \.html$
