name: Build and Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, java]
        version: [3.10.12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        if: ${{ matrix.language == 'python' }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Set up Java
        if: ${{ matrix.language == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  
          java-version: '21.0.4'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS
        run: ../style.scss:../assets/stylesheets/output.css

      - name: Run Python tests
        run: |
          python3 -m unittest discover tests

      - name: Build and test Java
        run: |
          echo "Building and testing Java"
          javac -version
          java -version
