name: Build and Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, java, go]
        version: [3.8, 3.9, 3.10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        if: ${{ matrix.language == 'python' }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Set up Java
        if: ${{ matrix.language == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.version }}

      - name: Set up Go
        if: ${{ matrix.language == 'go' }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}

      - name: Install Python dependencies
        if: ${{ matrix.language == 'python' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        if: ${{ matrix.language == 'python' }}
        run: |
          python -m unittest discover tests

      - name: Build and test Java
        if: ${{ matrix.language == 'java' }}
        run: |
          echo "Build and test Java"

      - name: Build and test Go
        if: ${{ matrix.language == 'go' }}
        run: |
          echo "Build and test Go"
