name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        run: pylint run_server.py

  htmlhint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: Compile SCSS
        run: sass path/to/input.scss:path/to/output.css

      - name: Run htmlhint
        run: htmlhint about.html

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run trufflehog
        uses: trufflesecurity/trufflehog@v3
